sudo: required
dist: bionic
addons:
  hosts:
    - iemdb2.local
    - iemdb-hads.local
    - iemdb-iemre.local
    - iemdb-mos.local
    - iem.local
    - iem-memcached
    - iemdb-talltowers.local
    - iem-web-services.local
    - iemdb-postgis.local
    - iemdb-mesosite.local
    - iemdb-afos.local
    - iemdb-asos.local
    - iemdb-snet.local
    - iemdb-mos.local
    - iemdb-rwis.local
    - iemdb-squaw.local
    - iemdb-awos.local
    - iemdb-iem.local
    - iemdb-other.local
    - iemdb-scan.local
    - iemdb-wepp.local
    - iemdb-coop.local
    - iemdb-isuag.local
    - iemdb-portfolio.local
    - iemdb-smos.local
language: python
env:
  global:
    # Prevent extraneous log messages
    - DEBIAN_FRONTEND=noninteractive
before_install:
  - git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
  - . .ci_tooling/postgres.sh
install:
  # https://travis-ci.community/t/t/712/12
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres || true

script:
  - sh bootstrap.sh
  - python schema_manager.py
